In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
import numpy as np

In [3]:
iris = datasets.load_iris()
inputs = iris.data
targets = iris.target
inputs = np.asarray(inputs)
targets = np.asarray(targets)

In [4]:
xtrain = inputs[:-10] 
xtest = inputs[-10:]
ytrain = targets[:-10]
ytest = targets[-10:]


TypeError: shuffle() takes exactly one argument (2 given)

In [86]:
obj = KNeighborsClassifier()

In [87]:
obj.fit(xtrain, ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [88]:
xtest[0]

array([ 6.7,  3.1,  5.6,  2.4])

In [89]:
ya =ytest

In [90]:
yp = obj.predict(xtest)

In [91]:
yp

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [92]:
ya

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [93]:
yp

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [94]:
from sklearn import metrics

In [71]:
acc = metrics.accuracy_score(ya, yp)*100
# We are getting the accuracy of the 100%
acc

100.0

In [106]:
acc 

100.0