In [130]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
x = np.array([[10, 9, 2, 15, 10, 16, 11, 16]], dtype=np.int16)

In [131]:
y = np.array([[95, 80, 10, 50, 45, 98, 38, 93]], dtype=np.int16)

In [132]:
x = x.reshape(8,1)
y = y.reshape(8,1)
x.shape

(8, 1)

In [133]:
p = LinearRegression()

In [134]:
x.shape

(8, 1)

In [135]:
x.shape

(8, 1)

In [136]:
y.shape

(8, 1)

In [137]:
x.reshape(8,-1)
x.shape

(8, 1)

In [138]:
x

array([[10],
       [ 9],
       [ 2],
       [15],
       [10],
       [16],
       [11],
       [16]], dtype=int16)

In [139]:
p.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [140]:
p.predict(x)

array([[ 58.46361406],
       [ 53.87571545],
       [ 21.76042518],
       [ 81.40310711],
       [ 58.46361406],
       [ 85.99100572],
       [ 63.05151267],
       [ 85.99100572]])

In [141]:
p.intercept_

array([ 12.58462796])

In [142]:
p.fit_intercept

True

In [148]:
c = p.intercept_
c

array([ 12.58462796])

In [149]:
m = p.coef_
m

array([[ 4.58789861]])

In [162]:
y = m*x+c
?pd.DataFrame([10, 9, 2, 15, 10, 16, 11, 16], [95, 80, 10, 50, 45, 98, 38, 93], index = ["a", "b"])

In [147]:
data 

0
95  10
80   9
10   2
50  15
45  10
98  16
38  11
93  16

In [185]:
o = pd.DataFrame()

AttributeError: 'numpy.ndarray' object has no attribute 'endswith'

AttributeError: 'numpy.ndarray' object has no attribute 'endswith'

In [183]:
o["input"] = x
o["output"] = y

ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series

0  input  output
0  10     10      10
1   9      9       9
2   2      2       2
3  15     15      15
4  10     10      10
5  16     16      16
6  11     11      11
7  16     16      16