# data 28 - 08-18

In [65]:
## A package is the collection of  lot of the classes
## static , instance , local varriable
## a class is the collection of the properties(member variiable) and the functions ()
## Numpy
## Panda
## matplotlib

## Cv2
## compiler convert the source code into the machine code (.obj file) 

## import PK ( PK package imported )
### less time consuming from Pk import pk.c3.m3
### ease of the access import pulkit as p

### Data should be tabular

### numpy is extension for the python#
### for the scientific computing
### 90 % data is in the 2D

 ROWS  -> 
 columns -> features

In [66]:
import numpy as np

In [67]:
my_array1d = np.array([1,2,3,3,23,23,23])

In [68]:
print(type(my_array1d))

<class 'numpy.ndarray'>


In [69]:
my_array1d.dtype

dtype('int32')

In [70]:
my_array1d.size

7

In [71]:
my_array1d.itemsize

4

In [72]:
len(my_array1d)

7

In [73]:
# for 1 d size == length (nut only for the one dimension array)
# it return the total number of the hnumber of the elements of the array

In [74]:
# why this is not giving the error
my_array1d[0:1000]

array([ 1,  2,  3,  3, 23, 23, 23])

In [75]:
len(my_array1d)

7

In [76]:
my_array1d[2:6:2]

array([ 3, 23])

In [77]:
my_array1d.ndim

1

In [87]:
my_data2d = np.array([[1,2 ,3],[4,5,6],[6,7,8]], dtype =np.float64) 

In [88]:
my_data2d.ndim

2

### IN  the 2D the shape - > return the rows and the column
### length - > no of the list in the array
###### size  -> total number of the elements

In [89]:
my_data2d.dtype

dtype('float64')

In [91]:
# return the size of the elements of the one varriable
my_data2d.itemsize

8

In [93]:
my_data2d.argmax()

8

In [99]:
# my_data2d[rows, column, step]

In [106]:
my_data2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6.,  7.,  8.]])

In [111]:
my_data2d[:2,1:3]

array([[ 2.,  3.],
       [ 5.,  6.]])

In [123]:
my_data2d[0:3:2,:3:2]

array([[ 1.,  3.],
       [ 6.,  8.]])

In [129]:
# [start : end : stepsize]
my_data2d[1:3:1,1:3:1]

array([[ 5.,  6.],
       [ 7.,  8.]])

In [132]:
my_data2d[::-1,::-1]

array([[ 8.,  7.,  6.],
       [ 6.,  5.,  4.],
       [ 3.,  2.,  1.]])

In [141]:
my_data2d.mean()

4.666666666666667

In [142]:
my_data2d.std()

2.2110831935702664

In [145]:
my_data2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6.,  7.,  8.]])

In [147]:
sum(my_data2d.diagonal())

14.0

In [149]:
a = np.zeros((4,4), dtype=np.float64)

In [150]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [155]:
b  = a = np.ones((4,4), dtype=np.float64)

In [156]:
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [162]:
c = np.eye(3)
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])